import type { ArticleExtension } from "./types";

export const continuityExtension: ArticleExtension = {
  images: { second: "/blog/task-continuity-across-agents-a.webp" },
  en: {
    secondCaption: "Generated illustration of successive workstations and a bounded transfer. It is a concept, not a record of a completed handoff.",
    sections: [
      { heading: "A Task is the durable story", paragraphs: [
        "Imagine asking an agent to repair a failing test, then leaving the desk. Its native session may inspect files, delegate a narrow search to a child agent, and stop when it needs permission to run a command. Those are events within one user request. If a provider window closes, the user's objective has not become a new objective. A stable Task lets the phone present the same work, its next decision, and its execution history without treating every session boundary as a fresh assignment.",
        "This distinction matters most when a second provider or computer enters the picture. The new execution should know which Task it serves and which facts were deliberately carried forward. It should not be asked to inherit invisible reasoning or assume that a summary is a full transcript. The human-visible record can preserve the objective, decisions, blockers, and evidence references, while the provider keeps its own native session semantics. Continuity is a claim about traceable work, not identical internal state.",
      ] },
      { heading: "Build a handoff that can be inspected", paragraphs: [
        "A useful capsule names the source execution, intended target, repository and revision, relevant constraints, and the work still open. It distinguishes observed facts from the previous agent's interpretation. For example, ‘test command exited with code one’ is stronger than ‘the tests look broken’; the command, exit result, and time let the next person verify the statement. A short handoff can be safer than a large transcript if it is explicit about what it omits.",
        "The destination should acknowledge acceptance rather than silently appearing to continue. Acceptance means the route reached a compatible session; it does not mean the destination understood every detail or completed the task. If it cannot start because the machine is offline, the provider is unavailable, or the target checkout differs, the Task should keep the failed or pending route visible. This prevents a queued action from masquerading as productive work.",
      ] },
      { heading: "Repository state is part of the route", paragraphs: [
        "A task about code depends on more than its title. The next execution needs to know which repository and checkout it is entering, whether the branch has uncommitted changes, and whether another agent claims the same files. A path alone is ambiguous across computers; a branch name alone does not guarantee identical contents. Attach revision and resource context to the route, and require the receiving execution to report what it actually sees before it edits.",
        "Consider two agents preparing changes to the same module. Separate worktrees isolate their files, but do not settle the product decision about which result to keep. Resource claims make likely overlap visible, and a later review resolves it. A receipt that merely says ‘accepted’ is therefore not a merge result. The Task should expose the chain from routing to code review and verification, with room for conflict and uncertainty.",
      ] },
      { heading: "What the phone can decide", paragraphs: [
        "The phone is useful for small, well-scoped choices: continue this Task on a named computer, answer an approval request, or inspect the latest result. It should show the action's target and consequences before a tap. A vague button saying ‘continue’ is insufficient when several computers and providers are available. The person needs to know whether they are resuming an existing execution, starting a supported new one, or only queuing a message for later delivery.",
        "The phone is not a replacement for checking a diff, rerunning a failing test, or reviewing a security-sensitive operation on the computer when those steps require more context. A compact status can link to the right evidence and make the next human action clear. It should also be able to say ‘unknown’: no observed invocation is different from an observed failure, and both differ from a successful verified change.",
      ] },
      { heading: "A realistic end-to-end check", paragraphs: [
        "For a trial run, choose a modest Task and write down its objective before starting. Let one provider investigate it, record a decision or blocker, then request a supported handoff to a specific second execution. Inspect the capsule and the receiving receipt. Confirm that the second execution sees the intended repository state and can explain its next action. Finally, examine the code change and rerun the relevant test. Each step tests a different promise.",
        "If the provider or host does not support the requested remote start, stop at that boundary and use the supported continuation path. GrantTap's current handoff coverage is provider and target dependent; a concept diagram cannot expand it. The editorial image above illustrates successive workstations, while the in-app screenshot below uses deterministic demonstration data. Neither replaces the real receipt and code evidence from your own Task. The durable outcome is a decision trail a person can revisit.",
      ] },
    ],
  },
  ru: {
    secondCaption: "Сгенерированная схема последовательной работы и ограниченной передачи. Она не подтверждает, что handoff действительно состоялся.",
    sections: [
      { heading: "Task хранит историю запроса", paragraphs: [
        "Представьте просьбу исправить падающий тест. Агент изучает файлы, поручает дочернему агенту узкий поиск и останавливается, когда для команды требуется разрешение. Это события внутри одного запроса человека. Если окно провайдера закрывается, исходная цель не становится новой целью. Стабильная Task позволяет телефону показывать ту же работу, следующее решение и историю исполнений, не превращая каждую смену сессии в отдельное поручение.",
        "Различие особенно важно, когда в работу входит второй провайдер или компьютер. Новое execution должно знать, какую Task оно обслуживает и какие факты были намеренно переданы. Нельзя требовать от него невидимых рассуждений прежнего агента или считать краткое резюме полным transcript. Видимая человеку запись сохраняет цель, решения, блокеры и ссылки на evidence, а провайдер продолжает использовать собственную native session. Непрерывность означает прослеживаемую работу, а не тождественное внутреннее состояние.",
      ] },
      { heading: "Передача, которую можно проверить", paragraphs: [
        "Полезный capsule называет исходное execution, выбранную цель, репозиторий и revision, действующие ограничения и незавершённую работу. Он отличает наблюдаемые факты от интерпретаций прежнего агента. Например, запись «команда тестов завершилась с кодом один» сильнее, чем «тесты выглядят сломанными»: команда, результат и время позволяют проверить вывод. Короткая передача может быть надёжнее длинного transcript, если она честно перечисляет свои пропуски.",
        "Целевая сторона должна явно подтвердить приём вместо молчаливой видимости продолжения. Приём означает, что маршрут дошёл до совместимой сессии; он не означает понимания каждой детали или завершения Task. Если запуск невозможен из-за недоступной машины, неподдерживаемого провайдера или другого checkout, причина остаётся видимой в Task. Тогда действие в очереди не выглядит как уже выполняющаяся работа.",
      ] },
      { heading: "Состояние репозитория — часть маршрута", paragraphs: [
        "Задача о коде зависит не только от названия. Следующему execution нужно знать репозиторий и checkout, наличие незакоммиченных изменений и пересечение с работой другого агента. Один путь к папке неоднозначен на разных компьютерах; одинаковое имя ветки не гарантирует одинаковое содержимое. Добавьте к маршруту revision и сведения о занятых ресурсах, а принимающая сторона пусть сообщит, что она действительно видит до первой правки.",
        "Допустим, два агента готовят изменения одного модуля. Разные worktrees разделят файлы, но не примут продуктовое решение, какой результат нужен. Claims заранее показывают вероятное пересечение, а последующее review разрешает его. Receipt со словом «принято» поэтому не является результатом merge. Task должна показывать цепочку от маршрута до проверки кода и тестов, оставляя место конфликту и неизвестности.",
      ] },
      { heading: "Какие решения подходят телефону", paragraphs: [
        "Телефон удобен для небольших конкретных действий: продолжить Task на названном компьютере, ответить на запрос разрешения или посмотреть последний результат. До нажатия нужно видеть цель и последствия. Кнопки «продолжить» недостаточно, когда доступно несколько компьютеров и провайдеров. Человеку важно понимать, возобновляется ли существующее execution, запускается ли поддерживаемое новое или сообщение лишь ставится в очередь до восстановления связи.",
        "Телефон не заменяет просмотр diff, повтор падающего теста и внимательную оценку опасной команды на компьютере, когда для этого нужен широкий контекст. Краткий статус может вести к evidence и ясно формулировать следующее действие человека. Он также должен уметь сообщить «неизвестно»: отсутствие наблюдения о вызове отличается от наблюдаемой ошибки, а оба состояния отличаются от подтверждённого результата.",
      ] },
      { heading: "Как проверить весь сценарий", paragraphs: [
        "Для пробного запуска выберите небольшую Task и запишите её цель. Пусть один провайдер исследует проблему, зафиксирует решение или блокер, после чего запросите поддерживаемый handoff на конкретное второе execution. Изучите capsule и receipt принимающей стороны. Проверьте, что новая сессия видит нужный репозиторий и может объяснить следующий шаг. В конце осмотрите изменение кода и повторите нужный тест. Каждый этап проверяет отдельное обещание.",
        "Если провайдер или host не поддерживает удалённый старт, остановитесь на этой границе и воспользуйтесь поддерживаемым путём продолжения. Текущее покрытие handoff в GrantTap зависит от провайдера и цели; концептуальная схема его не расширяет. Иллюстрация выше показывает последовательные рабочие места, а снимок приложения ниже сделан на детерминированных демоданных. Ни один из них не заменяет реальный receipt и доказательства изменения вашей Task. Ценный итог — цепочка решений, к которой можно вернуться.",
      ] },
      { heading: "Когда продолжение лучше отложить", paragraphs: [
        "Не всякая Task должна немедленно переехать на другой компьютер. Если исходное execution оставило незакоммиченные изменения, принимающий host ещё не видит тот же checkout или требуемая capability не инициализирована, поспешный handoff добавит неопределённости. Сначала выясните, где находится фактический код и какой revision будет основой продолжения. Сохраните блокер в Task и выберите явный маршрут после проверки. Очередь полезна только тогда, когда человеку ясно, чего она ждёт и какое действие выполнится после восстановления связи.",
        "При возвращении к прерванной работе перечитайте не только последнее сообщение, но и принятые ранее ограничения. Например, отказ от опасной команды не должен потеряться после смены провайдера. Если capsule не содержит нужного решения, запросите уточнение вместо догадки. Стабильная Task помогает помнить эту историю, но не гарантирует понимания новым агентом. Поэтому перед первой правкой полезно попросить принимающее execution кратко назвать цель, ограничения и проверку, которую оно собирается выполнить. Такой ответ показывает возможное расхождение до изменения файлов.",
        "После завершения передачи проверьте историю исходного execution. Оно могло остаться доступным для просмотра, даже если больше не владеет Task. Не запускайте в нём новую правку случайно: это создаст две конкурирующие версии результата. Если продолжение всё же требуется на исходной машине, сначала определите владельца текущего шага и состояние ветки. Так Task сохраняет один понятный маршрут решений, а не две параллельные истории с одинаковым названием и разным кодом.",
      ] },
    ],
  },
};
