import type { ArticleExtension } from "./types";

export const cortexExtension: ArticleExtension = {
  images: { first: "/blog/cortex-loom-evidence-per-token-a.webp", second: "/blog/cortex-loom-evidence-per-token-b.webp" },
  en: {
    firstCaption: "Generated concept of selecting source-backed context from a larger repository. The image is not a measured token chart.",
    secondCaption: "Generated reminder to judge selected context by the coding result as well as its size. No depicted checks are real benchmark data.",
    sections: [
      { heading: "Define the denominator first", paragraphs: [
        "A percentage reduction is meaningful only when the compared quantities have the same boundary. The published ten-task probe reports selected context tokens for two approaches covering 40 declared facts: 403,238 for naive selection and 19,035 for verified Cortex source windows. The reported 95.3% reduction refers to that selection metric. It is not a claim that a model bill, wall-clock time, or every coding session falls by the same percentage. The repository also reports a delivered MCP envelope of 22,936 tokens, a different measurement.",
        "The estimate uses four characters per token. That convention is useful for reproducible comparison within the probe but differs from a provider's exact tokenizer and billing rules. A reader should therefore keep the units in the sentence: estimated selected context tokens under this benchmark. Removing those qualifiers turns a carefully scoped result into a marketing promise the source does not support.",
      ] },
      { heading: "Why the second number differs", paragraphs: [
        "The repository presents a separate live-server question with a detailed table. Reading candidate files used 79,040 session tokens; one Cortex context-profile call used 9,801, made of 454 schema and 9,347 payload tokens. Both paths found the four declared facts. A shorter README summary gives 4,167 for a Cortex figure without the same explicit table accounting. The article chooses the detailed table and tells readers about the discrepancy rather than combining unlike figures into a stronger ratio.",
        "This is a good habit for any efficiency report. State whether a number measures selected text, delivered tool payload, schema overhead, whole session, or billed usage. Check if the same tokenizer, task, and stopping rule apply. If one arm reads several files while another makes one tool call, that is a useful workflow comparison, but it still needs the defined task and fact target beside the number. The benchmark link provides those details for inspection.",
      ] },
      { heading: "Selection is not completion", paragraphs: [
        "A context packet can include all declared facts yet fail to help an agent make the right edit. The project's coding-agent matrix records a case where a much smaller packet did not improve the close class because it emphasized module maps over implementation detail. This is exactly the kind of result that a pure token chart hides. The engineering question is whether the next action became more accurate, testable, and complete, not only whether fewer bytes reached the model.",
        "For a reliable comparison, define a task before seeing the result. Record the source revision, facts to retrieve, model and tool setup, context size, coding action, and verification outcome. Report failed, missing, or rate-limited runs as such. Do not turn an unrun cell into a zero score. Provider accounting methods can differ, so cost numbers from different clients should not be added or ranked without a common boundary.",
      ] },
      { heading: "Where source windows help", paragraphs: [
        "A developer entering an unfamiliar repository often needs a small set of contracts, callers, and neighboring implementation details. A source-backed window can preserve a route from summary to exact file and line, making it easier to inspect a claim. This is different from copying a whole directory into the prompt or trusting an unsupported generated synopsis. When the question concerns cross-file behavior, narrowing the relevant windows can reduce distraction while keeping evidence reviewable.",
        "The method has limits. Dynamic behavior, generated artifacts, external services, and stale indexes may require direct inspection beyond the selected packet. A tiny edit in a known file may not justify a context compiler at all; Cortex's own guidance says to skip it in that case. Source selection should serve the decision at hand. It should never prevent the agent from opening more evidence when the packet is incomplete or the test result contradicts it.",
      ] },
      { heading: "A possible connection to GrantTap", paragraphs: [
        "GrantTap's supported handoff currently carries bounded Task and git facts. A future integration could select repository context for a receiving execution, attach source revision, and expose unknowns. That is a design direction, not a feature claim about today's cross-provider transfers. The phone should show why a handoff happened and where the next decision belongs; a receiving coding agent may need richer source windows on its computer to act well.",
        "The separation matters. A compact human-visible Task record and a model's code context have different audiences and failure modes. The first needs clear authority, destination, and status. The second needs enough implementation detail to make an edit and verify it. Compressing either indiscriminately can lose the fact that changes the decision. If Cortex evidence is ever incorporated, its value should be tested against actual task outcomes, not inferred from a stand-alone reduction percentage.",
      ] },
      { heading: "How to evaluate it for your repository", paragraphs: [
        "Choose a handful of real questions: find a caller, explain a contract, locate a failing path, and propose a narrow fix. Write the facts and acceptance checks before running either method. Compare ordinary file reading with source-window selection at the same revision. Count selected and delivered context separately; record any tool schema overhead and total session use where measurable. Then inspect whether the agent found the right source and whether the resulting change passed meaningful tests.",
        "The first generated image depicts source selection without numbers; the second emphasizes checking the coding result. The GrantTap screenshot below is a deterministic architecture fixture, not a Cortex benchmark interface. The published repository and detailed benchmark remain the sources for numerical claims. The practical conclusion is conditional: efficient context is valuable when it preserves needed evidence and improves a real decision. A smaller packet that leaves the Task unfinished is only smaller.",
      ] },
    ],
  },
  ru: {
    firstCaption: "Сгенерированная схема отбора контекста с привязкой к исходникам. Это не измеренный график токенов.",
    secondCaption: "Сгенерированное напоминание: размер контекста оценивают вместе с результатом правки. Нарисованные проверки не являются данными бенчмарка.",
    sections: [
      { heading: "Сначала определите знаменатель", paragraphs: [
        "Процент сокращения имеет смысл, только когда сравниваемые величины имеют общую границу. Опубликованный probe из десяти задач сообщает оценку отобранных токенов контекста для двух подходов, покрывающих 40 заданных фактов: 403 238 при наивном отборе и 19 035 для подтверждённых окон Cortex. Указанные 95,3% относятся именно к этому показателю отбора. Это не обещание такого же снижения счёта модели, времени или расхода любой coding-сессии. Отдельно репозиторий указывает доставленный MCP envelope в 22 936 токенов.",
        "Оценка построена на допущении четыре символа на токен. Оно помогает воспроизводимо сравнивать способы внутри probe, но отличается от точного tokenizer и биллинга провайдера. Поэтому единицы нужно оставлять рядом с числом: оценочные выбранные токены контекста в данном бенчмарке. Если убрать оговорку, аккуратно ограниченный результат превращается в рекламное обещание, которого источник не поддерживает.",
      ] },
      { heading: "Откуда другое число", paragraphs: [
        "Репозиторий описывает отдельный вопрос к живому серверу в подробной таблице. Чтение подходящих файлов заняло 79 040 токенов сессии; один вызов Cortex context-profile — 9 801, включая 454 токена схемы и 9 347 ответа. Оба пути нашли четыре заданных факта. Краткое резюме README приводит для Cortex число 4 167 без такого же явного табличного учёта. Статья выбирает подробную таблицу и прямо сообщает о расхождении вместо сложения несопоставимых цифр в более яркий ratio.",
        "Это полезная привычка для любого отчёта об эффективности. Уточняйте, измеряется ли выбранный текст, доставленный payload, накладные токены схемы, вся сессия или сумма в биллинге. Совпадают ли tokenizer, задача и правило остановки? Если один вариант читает файлы, а другой вызывает инструмент, это интересное сравнение процессов, но рядом всё равно нужны определённая задача и цель по фактам. Ссылка на бенчмарк позволяет проверить детали.",
      ] },
      { heading: "Отбор не равен завершению", paragraphs: [
        "Пакет контекста может включать все заданные факты, но не помочь агенту сделать правильную правку. Матрица coding-агентов проекта содержит случай, где гораздо меньший пакет не улучшил класс завершения, потому что в нём преобладали карты модулей вместо деталей реализации. Именно такой результат скрывает график одних токенов. Инженерный вопрос — стало ли следующее действие точнее, проверяемее и полнее, а не только получил ли model меньше байтов.",
        "Для надёжного сравнения задачу определяют до результата. Фиксируют revision исходников, необходимые факты, model и tool setup, размер контекста, действие с кодом и итог проверки. Не выполненные, отсутствующие и ограниченные rate limit прогоны называют своими именами. Ячейку без запуска нельзя превращать в нулевую оценку. Методы учёта провайдеров различаются, поэтому их стоимость нельзя складывать и ранжировать без общей границы.",
      ] },
      { heading: "Когда помогают окна исходников", paragraphs: [
        "Разработчику в незнакомом репозитории часто нужны несколько контрактов, callers и соседние детали реализации. Окно с привязкой к исходнику сохраняет путь от краткого контекста к точному файлу и строке, позволяя проверять утверждение. Это отличается и от копирования целой папки в prompt, и от веры в сгенерированный пересказ без опоры. Когда вопрос касается поведения между файлами, отбор подходящих окон может убрать шум, сохранив проверяемое evidence.",
        "У метода есть пределы. Динамическое поведение, generated artifacts, внешние сервисы и устаревший index могут требовать прямого просмотра за пределами пакета. Для маленькой правки известного файла context compiler может быть вовсе не нужен; документация Cortex советует его пропустить. Отбор должен служить конкретному решению. Он никогда не должен мешать открыть дополнительный исходник, если пакет неполон или тест противоречит его картине.",
      ] },
      { heading: "Возможная связь с GrantTap", paragraphs: [
        "Поддерживаемый handoff GrantTap сейчас переносит ограниченные факты Task и git. Будущая интеграция могла бы выбрать контекст репозитория для принимающего execution, добавить revision исходника и явно показать неизвестное. Это направление проектирования, а не заявление о нынешнем cross-provider переносе Cortex packets. Телефон показывает причину handoff и место следующего решения; принимающему coding-агенту могут потребоваться более полные окна исходников на компьютере.",
        "Разделение важно. Краткая видимая человеку запись Task и контекст кода для модели имеют разную аудиторию и разные риски. Первой нужны ясные полномочия, цель и статус. Второму — достаточно деталей реализации для правки и проверки. Безусловное сжатие любого из них способно выбросить решающий факт. Если evidence Cortex когда-либо включат в маршрут, пользу надо проверять по результатам реальных Tasks, а не выводить из отдельного процента экономии.",
      ] },
      { heading: "Как оценить на своём репозитории", paragraphs: [
        "Выберите несколько настоящих вопросов: найти caller, объяснить контракт, локализовать падающий путь и предложить узкое исправление. Запишите необходимые факты и критерии приёмки до запуска обоих способов. Сравните обычное чтение файлов и отбор окон на одной revision. Считайте выбранный и доставленный контекст отдельно; учитывайте накладные токены схемы и общий расход сессии, где это измеримо. Затем проверьте, найден ли нужный исходник и прошло ли изменение значимые тесты.",
        "Первая сгенерированная картинка показывает отбор без чисел; вторая напоминает проверить coding-результат. Скриншот GrantTap ниже — детерминированный fixture архитектуры, а не интерфейс бенчмарка Cortex. Источниками чисел остаются опубликованный репозиторий и подробный отчёт. Практический вывод условен: экономный контекст полезен, когда сохраняет нужное evidence и улучшает реальное решение. Меньший пакет, после которого Task остаётся незаконченной, просто меньше.",
      ] },
    ],
  },
};
