import type { ArticleExtension } from "./types";

export const linkedExtension: ArticleExtension = {
  images: { first: "/blog/linked-projects-without-merging-access-a.webp", second: "/blog/linked-projects-without-merging-access-b.webp" },
  en: {
    firstCaption: "Generated illustration of linked repositories with separate access boundaries; this is not a live Project map.",
    secondCaption: "Generated editorial view of declared and evidence-backed relations. The pictured links do not represent scanned customer code.",
    sections: [
      { heading: "Start with the coordination scope", paragraphs: [
        "A Project is the place where people coordinate work, not a command to merge every repository or every provider session. A mobile app, site, and local helper may contribute to one product while retaining separate checkouts and release processes. The Project view can link them so a person understands why two Tasks are related. The link should carry an explicit reason: shared product scope, a declared dependency, or a report with evidence. Those reasons have different strengths.",
        "The safest mental model is a map with boundaries. A map can show that two roads meet without handing a traveler a key to every building along them. Likewise, linking repositories should help navigation without broadening membership or capability policy. When someone joins a Project, the system must evaluate that person's grants and the owner's controls for each protected action. The picture alone is not an authorization rule.",
      ] },
      { heading: "Binding, declaration, and evidence", paragraphs: [
        "A repository binding says which checkout a Project may observe through a connected computer. A declared relationship says that someone has recorded a link between components or repositories. Evidence-backed architecture goes further: a report points to analyzed source and a revision. Conflating these categories creates false confidence. A visually impressive edge may be only a declaration, and even a verified edge may describe an older commit than the Task currently uses.",
        "Inspect the label before acting on a relation. Ask who supplied it, which source it covers, when it was produced, and whether it applies to this checkout. If a report is missing, preserve the declaration as a declaration rather than silently upgrading it. If a report is stale, it can still guide exploration but should not justify an automatic edit. This is a practical way to keep architecture discovery useful without pretending it is omniscient.",
      ] },
      { heading: "Permissions follow the person and action", paragraphs: [
        "Consider a teammate who may review a website Task but has no permission to run a local command on the release computer. A linked Project can still show that the site and release helper belong to the same product. It must not infer command access from that link. The relevant question is whether the member is allowed to receive the specific data or request the specific action at the chosen destination. The owner's phone and host enforcement have distinct roles in that chain.",
        "The same distinction applies to capability configuration. One computer may have an MCP server available while another has a different configuration or no credential. A common Project label does not make those hosts equivalent. When a Task moves, its target must report what it can actually initialize. The Project map can help choose a route, but the route still needs its own capability and policy checks.",
      ] },
      { heading: "Avoid identity mistakes", paragraphs: [
        "Names are helpful for people but poor unique identifiers. Two repositories can share a short name, and a single repository can appear under different folder names on two computers. A Project can also be renamed without changing its identity. Durable links should therefore use stable identifiers and revision context, while the UI shows friendly names as context. A mistaken match can route work to the wrong checkout or expose an unrelated Task in a shared view.",
        "When reviewing a map, look for the computer, repository origin, checkout revision, and relationship type, not just the node title. If any of those are unknown, do not fill the gap with a guess based on similar names. A good interface lets the person inspect the reason behind a link and correct a declaration without rewriting source history. That is more valuable than making every graph edge appear equally certain.",
      ] },
      { heading: "Use the map to make one decision", paragraphs: [
        "Suppose an iOS change depends on a relay contract. The Project map can lead from the app repository to the protocol repository, show whether the relation was declared or observed, and identify the current Task on each side. The next sensible step is to check the contract at the relevant revision and coordinate the two owners. The map should not claim that both builds pass, that a deployment happened, or that one repository's permission covers the other.",
        "The first generated picture emphasizes separate boundaries; the second emphasizes different kinds of relation. The GrantTap screenshot below is a deterministic demonstration, not a fresh scan of private repositories. Treat all three as explanations of how to read the product. For your own work, inspect binding details and evidence before relying on a link. This turns a collection of repositories into a navigable Project without erasing the decisions that keep access narrow.",
        "A useful follow-up is to test the map against one real change. Choose a contract shared by two repositories, identify its current source revision, and ask which Task owns the next edit on each side. Confirm that the people who can see the relation are also authorized for the particular data they need. Then run the relevant checks separately in each checkout. If the picture cannot lead to those concrete answers, improve the labels or bindings before treating the graph as a planning tool.",
      ] },
    ],
  },
  ru: {
    firstCaption: "Сгенерированная иллюстрация связанных репозиториев с отдельными границами доступа; это не живая карта Project.",
    secondCaption: "Сгенерированное различие между объявленной и подтверждённой связью. Рисунок не является сканированием клиентского кода.",
    sections: [
      { heading: "Начните с области координации", paragraphs: [
        "Project — место координации людей и работы, а не команда объединить все репозитории и сессии провайдеров. Мобильное приложение, сайт и локальный helper могут входить в один продукт, сохраняя отдельные checkout и процессы выпуска. Вид Project связывает их, чтобы человек понимал, почему две Task относятся друг к другу. У связи должна быть явная причина: общий продуктовый контекст, объявленная зависимость или отчёт с evidence. Эти причины имеют разную силу.",
        "Полезная модель — карта с границами. Карта может показать пересечение дорог, но не выдаёт путнику ключи от всех зданий вдоль них. Точно так же связь репозиториев помогает навигации, не расширяя членство и правила возможностей. Когда человек входит в Project, защищённые данные и действия требуют проверки его разрешений и правил владельца. Красивая линия на схеме сама по себе не даёт права доступа.",
      ] },
      { heading: "Привязка, декларация и evidence", paragraphs: [
        "Привязка репозитория сообщает, какой checkout Project наблюдает через подключённый компьютер. Объявленная связь означает, что кто-то записал отношение между компонентами или репозиториями. Подтверждённая архитектура требует большего: отчёт должен вести к проанализированному исходнику и revision. Смешение категорий создаёт ложную уверенность. Даже яркое ребро может быть лишь декларацией, а подтверждённое ребро — относиться к более старому commit, чем текущая Task.",
        "Прежде чем действовать по связи, изучите подпись. Кто её добавил, какие исходники она покрывает, когда получена и применима ли к этому checkout? Если отчёта нет, оставьте декларацию декларацией. Если отчёт устарел, он может направить исследование, но не должен автоматически оправдывать правку. Так архитектурное представление остаётся полезным и не притворяется знанием всего кода.",
      ] },
      { heading: "Права относятся к человеку и действию", paragraphs: [
        "Представим коллегу, которому разрешён review Task сайта, но запрещён запуск локальной команды на компьютере выпуска. Связанный Project всё равно может показать, что сайт и helper относятся к одному продукту. Из этого нельзя выводить право на команду. Нужно проверить, можно ли именно этому участнику получить конкретные данные или запросить действие на выбранной машине. Проверка телефона владельца и enforcement на host выполняют разные части этой цепочки.",
        "То же верно для конфигурации возможностей. На одном компьютере MCP-сервер доступен, на другом настроен иначе или не имеет credential. Общая метка Project не делает hosts одинаковыми. При передаче Task целевая сторона должна сообщить, что она действительно способна инициализировать. Карта помогает выбрать маршрут, но самому маршруту нужны собственные проверки capability и policy.",
      ] },
      { heading: "Не путайте имя с identity", paragraphs: [
        "Имена удобны человеку, но плохо работают как уникальные идентификаторы. Два репозитория могут иметь одинаковое короткое имя; один репозиторий бывает в папках с разными именами на двух компьютерах. Project можно переименовать, не изменив его identity. Устойчивые связи поэтому опираются на стабильные идентификаторы и revision, а интерфейс показывает понятные названия как контекст. Ошибочное совпадение может отправить работу в чужой checkout или показать не связанную Task.",
        "При чтении карты ищите компьютер, происхождение репозитория, revision checkout и тип связи, а не только подпись узла. Если что-то неизвестно, не заполняйте пробел догадкой по похожему имени. Хороший интерфейс позволяет узнать основание ребра и исправить декларацию, не переписывая историю исходников. Это ценнее, чем одинаково уверенный вид всех линий графа.",
      ] },
      { heading: "Как карта помогает принять решение", paragraphs: [
        "Допустим, изменение iOS зависит от контракта relay. Карта Project ведёт от репозитория приложения к репозиторию протокола, показывает, объявлена связь или наблюдалась, и помогает найти текущие Task с обеих сторон. Следующий разумный шаг — проверить контракт на нужной revision и согласовать работу владельцев. Карта не доказывает, что обе сборки проходят, публикация состоялась или разрешение одного репозитория покрывает другой.",
        "Первая сгенерированная картинка подчёркивает отдельные границы, вторая — разные основания связей. Скриншот GrantTap ниже получен из детерминированной демонстрации, а не из свежего анализа закрытых репозиториев. Все три изображения объясняют, как читать продукт. В своей работе проверьте детали привязки и evidence до того, как положиться на связь. Так коллекция репозиториев становится понятным Project, не стирая решения, которые сохраняют узкий доступ.",
      ] },
      { heading: "Если отчёты расходятся", paragraphs: [
        "У разных компьютеров могут быть разные checkout одного репозитория. Один report ещё описывает старую revision, другой построен после изменения контракта, а участник видит только разрешённую ему часть Project. Это не повод выбирать самый красивый граф. Сначала установите, какой компьютер и commit относятся к текущей Task, затем сравните область и время отчётов. Устаревший отчёт остаётся историческим evidence, но не получает статус актуального только потому, что пришёл из знакомого host.",
        "При расхождении полезно сформулировать узкий вопрос: какой файл подтверждает связь сейчас? Если ответа нет, отметьте отношение как непроверенное и откройте исходник на целевом checkout. Отсутствие анализа нельзя автоматически толковать как отсутствие зависимости. Равным образом наличие ребра не подтверждает доступ к ресурсу. Карта показывает, где искать; policy определяет, что разрешено; host сообщает, что реально применено. У этих слоёв могут быть разные времена обновления, поэтому единый зелёный индикатор скрывал бы важную разницу.",
      ] },
      { heading: "Перед общей работой", paragraphs: [
        "Когда два участника открывают связанные Tasks, договоритесь о владельце изменения и порядке проверки контрактов. Если один агент меняет приложение, а другой одновременно правит протокол, связь на карте не заменяет согласования версии. Запишите в Task используемые revisions, ожидаемый результат и способ проверки каждой стороны. При необходимости работайте в отдельных ветках или worktrees. Это сохраняет возможность увидеть конфликт до объединения кода, не выдавая участникам лишний доступ к машинам друг друга.",
        "После завершения проверьте не только список связанных репозиториев, но и доказательства результата: соответствующие тесты, сборки и review. Успех в одном checkout не доказывает успех во втором. Если deploy или выпуск ещё не выполнялись, так и запишите. Проектная карта полезна как маршрут к этим проверкам. Она становится опасной только тогда, когда её визуальную близость принимают за общую identity, общие права или автоматически подтверждённое поведение всех частей продукта.",
      ] },
    ],
  },
};
