import type { ArticleExtension } from "./types";

export const summitExtension: ArticleExtension = {
  images: { first: "/blog/aws-summit-tel-aviv-agentic-systems-a.webp", second: "/blog/aws-summit-tel-aviv-agentic-systems-b.webp" },
  en: {
    firstCaption: "AI-generated conference-inspired scene. It is not a photograph of AWS Summit Tel Aviv or a depiction of its actual stage.",
    secondCaption: "Generated editorial operating loop based on topics in the published agenda; the policy gate refers to separate AgentCore documentation.",
    sections: [
      { heading: "Read the program for what it says", paragraphs: [
        "The official agenda is a record of scheduled sessions and their descriptions, not evidence that a particular attendee adopted a practice or that a speaker delivered a specific conclusion. Its Building AI & Agentic Apps track is nevertheless revealing as an editorial source. Building production-grade applications appears alongside running agentic systems, best practices, and scaling through optimization, observability, and evaluation. The juxtaposition invites a practical question: what changes once an agentic demo must operate repeatedly under real conditions?",
        "The event overview also presents agentic AI among broader cloud and serverless topics. It would be inaccurate to say the entire Summit was solely about governance or that governance was a named session in this track. The first generated image is deliberately conference-inspired, not documentary photography. We rely on the linked AWS pages for dates, session titles, and descriptions; the visual conveys the theme without pretending to record the room.",
      ] },
      { heading: "Building is only the first stage", paragraphs: [
        "A prototype can show a model receiving a request and calling a tool. Repeated operation introduces other questions: what input was accepted, which tool identity was selected, how a timeout is handled, and how a person can inspect a result. These are general engineering questions, not quotes from a Summit talk. Their relevance follows from placing development, running, optimization, observation, and evaluation in one program track.",
        "An evaluation should name the task it measures and the outcome it considers successful. A trace can explain an execution path, but tracing alone does not say whether the answer was useful. Optimization can reduce cost or latency while harming completeness. These concepts need to remain separate. The agenda suggests that teams are discussing them together; it cannot prove that any one architecture solves them for every application.",
      ] },
      { heading: "Governance comes from another source", paragraphs: [
        "AWS AgentCore Policy documentation provides a distinct example of governance: policy evaluation for requests routed through an AgentCore gateway, with decisions recorded. This is separate from the Summit agenda. Its scope matters. A gateway can enforce the calls that pass through it, but the documentation does not make a local shell command or every provider-native coding route flow through that gateway. We should not transfer a cloud service guarantee to a different execution path by analogy.",
        "The broader lesson is still useful. A human or organization chooses a rule, an execution boundary applies it, and evidence shows what happened. If an action takes another path, the claim of enforcement must narrow accordingly. In a local coding product, that boundary is often the connected computer and its provider integration. The second generated illustration puts a policy gate beside the operating loop to show a related question, not a session that appeared on the conference stage.",
      ] },
      { heading: "Why observability alone is insufficient", paragraphs: [
        "A dashboard can show that an agent ran. It may not show whether its action was authorized, whether the right computer executed it, or whether the resulting code passed tests. Observability helps locate events and failures; evaluation judges a defined outcome; governance constrains certain actions. All three are valuable, but none should silently stand in for the others. A request accepted by a gateway is not a verified business result, just as a prompt delivered to a coding provider is not a completed Task.",
        "A practical evidence chain might name the request, selected rule, enforcement decision, actual invocation, and independent result. If the result is unknown, keep it unknown. If a model answer is reviewed but the deployment has not run, report that distinction. These distinctions are especially important on a phone, where compact presentation can tempt teams to collapse several states into one attractive success badge.",
      ] },
      { heading: "The local coding analogy", paragraphs: [
        "GrantTap follows Tasks across supported local coding executions. The comparison to AWS infrastructure is about questions, not identical products. Which host is responsible? What capability is requested? Which policy was applied? Did a tool run? What did tests or a reviewer verify? Those questions make sense whether an application is hosted in a cloud service or a coding agent works on a developer's laptop, although the actual enforcement mechanisms differ.",
        "GrantTap's current coverage also has limits: provider routes differ, Cursor is Beta, complete cross-host capability bundle transfer is unfinished, and unknown usage remains unknown. The point of citing a conference program is not to claim endorsement. It is to connect a public discussion of building, running, observing, and evaluating agents to specific decisions a local product must make. The product should be assessed on those decisions and on evidence from its actual host path.",
      ] },
      { heading: "A disciplined takeaway", paragraphs: [
        "Use the Summit program as a reading list and prompt for design review. For a system you operate, pick one agent workflow and identify its builder, runtime, observation path, evaluation criterion, and policy boundary. Then try a failure: an unavailable tool, a delayed response, or an action denied at the boundary. Can a person tell what happened and what remains unresolved? That exercise is more informative than repeating a broad claim that ‘agents are the future.’",
        "The official sources below support the event date, published track, and AgentCore policy example. Our conclusion about an operational turn is an inference from those sources, not a report of attending the conference. The actual GrantTap screen below uses deterministic sample usage and does not show AWS data. The article's central theme is therefore deliberately modest: as agentic applications grow, trustworthy operation requires a traceable path from decision through execution to a checked result.",
      ] },
    ],
  },
  ru: {
    firstCaption: "Сгенерированная сцена по мотивам технологической конференции. Это не фотография AWS Summit Tel Aviv и не его реальная сцена.",
    secondCaption: "Сгенерированная схема эксплуатации по темам программы; policy gate относится к отдельной документации AgentCore.",
    sections: [
      { heading: "Читайте программу буквально", paragraphs: [
        "Официальная программа фиксирует запланированные сессии и описания, но не доказывает, что конкретный участник принял практику или докладчик произнёс определённый вывод. Тем не менее трек Building AI & Agentic Apps важен как редакционный источник. Разработка production-grade приложений стоит рядом с запуском агентных систем, лучшими практиками и масштабированием через оптимизацию, observability и evaluation. Это соседство подводит к вопросу: что меняется, когда демо должно многократно работать в реальных условиях?",
        "Общая страница события помещает agentic AI среди других облачных и serverless тем. Было бы неверно назвать весь Summit конференцией только о governance или представить governance отдельной сессией данного трека. Первая сгенерированная картинка вдохновлена конференцией, но не является репортажной фотографией. Дату, названия и описания сессий подтверждают страницы AWS ниже; изображение лишь передаёт тему и не притворяется записью зала.",
      ] },
      { heading: "Разработка — только начало", paragraphs: [
        "Прототип может показать, как модель получает запрос и вызывает инструмент. При регулярной эксплуатации возникают другие вопросы: какой input принят, какая identity инструмента выбрана, что делать с timeout и как человек проверит результат. Это общие инженерные вопросы, а не цитаты из доклада Summit. Их уместность следует из того, что в одном треке стоят разработка, запуск, оптимизация, наблюдение и оценка.",
        "Оценка должна назвать задачу и критерий успеха. Trace объясняет путь исполнения, но сам по себе не говорит, полезен ли ответ. Оптимизация способна снизить стоимость или задержку и одновременно ухудшить полноту. Эти понятия важно разделять. Программа показывает, что темы обсуждаются рядом; она не доказывает, что одна архитектура одинаково решает их для любого приложения.",
      ] },
      { heading: "Governance — из другого источника", paragraphs: [
        "Документация AWS AgentCore Policy даёт отдельный пример governance: проверка политикой запросов, идущих через gateway AgentCore, с записью решений. Это не утверждение из программы Summit. Область действия важна. Gateway может контролировать вызовы, проходящие через него, но документация не заставляет локальную shell-команду или каждый native путь coding-провайдера использовать этот gateway. Нельзя переносить обещание облачного сервиса на иной маршрут только по аналогии.",
        "Общий урок при этом полезен. Человек или организация выбирает правило, граница исполнения применяет его, а evidence показывает исход. Если действие идёт другим путём, заявление об enforcement должно становиться уже. В локальном coding-продукте такой границей часто выступают подключённый компьютер и интеграция провайдера. Вторая иллюстрация ставит policy gate рядом с рабочим циклом как связанный вопрос, а не как якобы показанную на сцене сессию.",
      ] },
      { heading: "Почему наблюдаемости мало", paragraphs: [
        "Dashboard может показать, что агент работал. При этом он не обязательно доказывает разрешённость действия, правильность выбранного компьютера или прохождение тестов после правки. Observability помогает находить события и ошибки; evaluation оценивает определённый результат; governance ограничивает некоторые действия. Все три нужны, но не подменяют друг друга. Принятый gateway запрос не равняется проверенному бизнес-результату, как доставленный coding-провайдеру prompt не равняется завершённой Task.",
        "Практическая цепочка evidence называет запрос, выбранное правило, решение enforcement, фактический вызов и независимый итог. Неизвестный результат остаётся неизвестным. Если ответ модели просмотрен, но deploy ещё не выполнялся, покажите различие. Особенно важно это на телефоне: компактный экран провоцирует объединить несколько состояний в один красивый бейдж успеха.",
      ] },
      { heading: "Аналогия с локальным coding", paragraphs: [
        "GrantTap ведёт Tasks через поддерживаемые локальные executions. Сравнение с AWS относится к вопросам, а не к тождеству продуктов. Какой host отвечает за действие? Какая capability запрошена? Какая policy применена? Вызван ли инструмент? Что подтвердили тесты или reviewer? Такие вопросы имеют смысл и для облачного приложения, и для coding-агента на ноутбуке разработчика, хотя реальные механизмы применения правил различаются.",
        "У GrantTap есть пределы текущего покрытия: маршруты провайдеров разные, Cursor в Beta, полный перенос bundles между hosts не завершён, неизвестный usage остаётся неизвестным. Ссылка на программу конференции не означает поддержку GrantTap со стороны AWS. Она связывает публичное обсуждение разработки, запуска, наблюдения и оценки агентов с конкретными решениями локального продукта. Оценивать продукт нужно по этим решениям и по evidence на его фактическом маршруте host.",
      ] },
      { heading: "Практический вывод", paragraphs: [
        "Используйте программу Summit как список тем для review. Для одного своего агентного сценария определите, кто его строит, где он выполняется, как наблюдается, по какому критерию оценивается и где проходит policy boundary. Затем вызовите сбой: инструмент недоступен, ответ задержан или действие запрещено на границе. Может ли человек понять, что произошло и что осталось нерешённым? Такая проверка информативнее общего лозунга о будущем агентов.",
        "Официальные источники ниже подтверждают дату события, опубликованный трек и пример AgentCore policy. Наш вывод о переходе к вопросам эксплуатации — интерпретация этих материалов, а не репортаж с конференции. Экран GrantTap ниже содержит детерминированный пример usage и не показывает данных AWS. Центральная мысль статьи поэтому конкретна: по мере роста agentic systems доверие требует прослеживаемого пути от решения через выполнение к проверенному результату.",
      ] },
    ],
  },
};
