export const copy = {
  en: {
    cta: "TestFlight by invitation",
    eyebrow: "Personal live control for local coding agents",
    heroTitle: "All your coding agents.",
    heroAccent: "One live control center.",
    hero: "Coordinate Claude Code, Codex, Cursor, and Grok Build across your computers. See work, govern capabilities and approvals, and continue from Mac, iPhone, iPad, or Apple Watch.",
    heroAction: "See availability",
    productAction: "See the product",
    proofs: ["Claude Code · Codex · Cursor · Grok Build", "Mac · iPhone · iPad · Watch", "End-to-end encrypted", "Mesh Governance"],
    providers: "Supported integrations",
    cursor: "Cursor Beta",
    grok: "Grok Build · Experimental",
    additional: "Provider-specific controls stay intact",
    productKicker: "See · Decide · Continue",
    productTitle: "Know what is happening now—and where you are needed.",
    productText: "GrantTap coordinates local agents, Mesh policy, auto-accept, shared evidence, and human decisions across devices.",
    scenarios: [
      ["Needs You", "Approvals, questions, and failed deliveries appear before everything else."],
      ["Working", "See the agent, model, computer, workspace, and latest useful activity."],
      ["Usage", "Find context pressure, observed tool failures, and actions worth taking."],
      ["Governance", "Allow, ask, or deny skills, MCP servers, and shell in a Mesh. Auto-accept runs only after effective policy permits a call, and computers report enforcement coverage."],
    ],
    meshKicker: "Mesh",
    meshTitle: "One Mesh. Connected repositories, Tasks, people, and agents.",
    meshText: "A stable Task spans agents and computers. Its distributed evidence graph connects dependencies, resource claims, Knowledge, and handoff receipts without copying transcripts or hidden reasoning.",
    meshQuestions: [
      ["Who is working?", "See the agent, computer, task, branch, and current owner."],
      ["Who depends on whom?", "Catch blockers and overlapping resource claims before they become merge conflicts."],
      ["Where are you needed?", "Technical questions stay agent-to-agent. Product, security, destructive, and unresolved conflicts reach Needs You."],
    ],
    shareKicker: "Shared Mesh",
    shareTitle: "Two people, connected work, explicit access.",
    shareText: "Grant repository access to a company account, pair a device, then separately grant that device access to selected Mesh spaces. Your phone checks both grants before forwarding Mesh data or actions.",
    shareFacts: [
      ["Company account", "Grant one, selected, or all repository IDs to a person. This alone does not join a Mesh or change Git provider access."],
      ["Invite with a role", "Viewer, Member, or Admin—and the permissions under it: reading and posting Mesh messages, Governance, creating Tasks, using an allowed computer, choosing a host model, and pinning execution."],
      ["Pin the host", "A Mesh can pin new Tasks to one confirmed computer. The display name is not the route. Offline, the request is refused or queued until a deadline—there is no silent fallback."],
      ["A refusal says why", "What a role does not allow never reaches a computer, and the member's phone is told which rule stopped it."],
      ["Release a stuck claim", "A claim left behind by an agent that is gone is released by the person. The computer answers, and a refusal puts the claim back with the reason."],
    ],
    meshGalleryKicker: "Mesh, screen by screen",
    meshGalleryTitle: "See the Mesh alongside the Task it coordinates.",
    meshCaptures: [
      ["iphone-project-mesh", "Mesh", "Find connected work from the current Mesh tab."],
      ["iphone-linked-projects", "Linked Mesh", "Repository bindings link spaces without merging their access."],
      ["iphone-governance", "Governance", "Review capability rules and each computer’s enforcement status."],
    ],
    howKicker: "How it works",
    howTitle: "One secure path back to the same local task.",
    steps: [
      ["Connect", "Run granttap setup. Pair iPhone or iPad with a one-time QR; a GrantTap passkey can approve coding-app access on a Mac with the local bridge. Passkey sign-in alone does not pair a phone."],
      ["Decide", "Allow, deny, answer, or retry when the exact session asks for you."],
      ["Continue", "Open the visible timeline and send the next turn with voice, photos, or files."],
    ],
    galleryKicker: "The real app",
    galleryTitle: "Mesh control on iPhone and iPad. Fast decisions on Apple Watch.",
    phoneCaption: "Now prioritizes Needs You, at-risk work, active sessions, and a short recent list.",
    tasksCaption: "Tasks shows the current computer, provider, Mesh, state, and context pressure.",
    taskCaption: "The task opens directly into a dated chat with the current Mesh, composer, and controls close by.",
    usageCaption: "Usage turns context pressure and observed tool outcomes into concrete next actions.",
    watchCaption: "Watch is for a glance, a decision, a short reply, or a new voice task.",
    openCapture: "Open full-size",
    closeCapture: "Close preview",
    securityKicker: "Native E2EE",
    securityTitle: "The relay routes ciphertext. It cannot read your tasks.",
    securityText: "Native iPhone and Apple Watch traffic is end-to-end encrypted. Pairing keys, task keys, provider credentials, prompts, commands, and replies never enter readable relay storage.",
    securityFacts: [
      ["On your computers", "Coding agents and provider credentials stay local."],
      ["On the relay", "Only bounded routing metadata, ciphertext, expiry, and wake metadata are visible."],
      ["On your devices", "Authorized endpoints decrypt the task and keep each task key isolated."],
    ],
    installKicker: "Install",
    installTitle: "Install the plugin. Connect on this computer.",
    installText: "Add GrantTap in Codex, Claude Code, Cursor Marketplace, or Grok Build, then run granttap setup. Pair your phone with the QR in the connection card. On a Mac with the local bridge, granttap.com/connect can also approve coding-app access with your GrantTap passkey. Do not add GrantTap in Cursor Customize → MCPs.",
    source: "Source",
    npm: "npm",
    relay: "Relay",
    pricingKicker: "Personal",
    pricingTitle: "From $1.99 per month after a 7-day free trial.",
    pricingText: "$1.99 for one computer, $3.99 for five, $5.99 for ten. Unlimited agents on each. Cancel through Apple at any time.",
    pricingAction: "Pricing and terms",
    releaseKicker: "Availability",
    releaseTitle: "Submitted to the App Store.",
    releaseText: "GrantTap 1.0 is waiting for App Review. TestFlight access is available by invitation while Apple reviews the release.",
    tagline: "See what your coding agents are doing. Step in when they need you.",
  },
  ru: {
    cta: "TestFlight по приглашению",
    eyebrow: "Personal live control для локальных coding agents",
    heroTitle: "Все ваши coding agents.",
    heroAccent: "Один live control center.",
    hero: "Координируйте Claude Code, Codex, Cursor и Grok Build на разных компьютерах. Следите за работой, управляйте правами и подтверждениями, продолжайте с Mac, iPhone, iPad или Apple Watch.",
    heroAction: "Проверить доступность",
    productAction: "Посмотреть продукт",
    proofs: ["Claude Code · Codex · Cursor · Grok Build", "Mac · iPhone · iPad · Watch", "Сквозное шифрование", "Mesh Governance"],
    providers: "Поддерживаемые интеграции",
    cursor: "Cursor Beta",
    grok: "Grok Build · Experimental",
    additional: "Provider-specific controls сохраняются",
    productKicker: "See · Decide · Continue",
    productTitle: "Понимайте, что происходит сейчас и где нужны именно вы.",
    productText: "GrantTap связывает локальных агентов, правила Mesh, авторазрешение, общие свидетельства и решения человека на всех устройствах.",
    scenarios: [
      ["Needs You", "Подтверждения, вопросы и ошибки доставки всегда выше остального."],
      ["Working", "Видны agent, model, computer, workspace и последнее полезное событие."],
      ["Usage", "Давление context, наблюдаемые ошибки tool calls и конкретные действия."],
      ["Governance", "Разрешайте, спрашивайте или запрещайте skills, MCP-серверы и shell внутри Mesh. Авторазрешение работает после проверки правил, а компьютеры сообщают покрытие исполнения."],
    ],
    meshKicker: "Mesh",
    meshTitle: "Один Mesh. Связанные репозитории, задачи, люди и агенты.",
    meshText: "Стабильная Task переживает смену агента и компьютера. Распределённый граф свидетельств связывает зависимости, resource claims, Knowledge и handoff receipts без копирования transcripts и hidden reasoning.",
    meshQuestions: [
      ["Кто работает?", "Видны agent, computer, task, branch и текущий owner."],
      ["Кто от кого зависит?", "Blockers и пересекающиеся resource claims обнаруживаются до merge conflict."],
      ["Где нужны вы?", "Технические вопросы остаются между агентами. Product, security, destructive и неразрешимые конфликты попадают в Needs You."],
    ],
    shareKicker: "Общий Mesh",
    shareTitle: "Два человека, связанная работа и явные права.",
    shareText: "Выдайте аккаунту компании доступ к репозиториям, привяжите устройство и отдельно дайте ему доступ к выбранным Mesh. Перед пересылкой данных и действий телефон проверяет оба разрешения.",
    shareFacts: [
      ["Аккаунт компании", "Дайте человеку доступ к одному, выбранным или всем ID репозиториев. Сам по себе он не добавляет в Mesh и не меняет права в Git-провайдере."],
      ["Приглашение с ролью", "Viewer, Member или Admin — с правами на чтение и отправку сообщений Mesh, Governance, создание задач, executor, модель хоста и закрепление выполнения."],
      ["Закрепить хост", "Mesh может закрепить новые задачи за одним подтверждённым компьютером. Имя на экране не маршрут. Офлайн — отказ или очередь до дедлайна, без тихого запасного хоста."],
      ["Отказ называет причину", "То, что роль не разрешает, не доходит до компьютера, а телефон участника узнаёт, какое правило это остановило."],
      ["Снять зависший claim", "Claim, оставленный исчезнувшим агентом, снимает человек. Компьютер отвечает, а при отказе claim возвращается с причиной."],
    ],
    meshGalleryKicker: "Mesh по экранам",
    meshGalleryTitle: "Mesh рядом с задачей, которую он координирует.",
    meshCaptures: [
      ["iphone-project-mesh", "Mesh", "Связанная работа в актуальной вкладке Mesh."],
      ["iphone-linked-projects", "Связанные Mesh", "Привязки репозиториев связывают пространства, сохраняя раздельные права."],
      ["iphone-governance", "Governance", "Правила возможностей и состояние исполнения на каждом компьютере."],
    ],
    howKicker: "Как работает",
    howTitle: "Один защищённый путь обратно в ту же локальную задачу.",
    steps: [
      ["Подключите", "Выполните granttap setup. iPhone или iPad подключается по одноразовому QR. На Mac с локальным мостом доступ coding app можно также подтвердить passkey GrantTap. Сам вход по passkey телефон не подключает."],
      ["Решите", "Разрешите, запретите, ответьте или повторите доставку для точной session."],
      ["Продолжите", "Откройте timeline и отправьте следующий ход голосом, с фото или файлом."],
    ],
    galleryKicker: "Настоящее приложение",
    galleryTitle: "Управление Mesh на iPhone и iPad. Быстрые решения на Apple Watch.",
    phoneCaption: "Now сначала показывает Needs You, риски, активные задачи и короткий recent list.",
    tasksCaption: "В Tasks видны компьютер, провайдер, Mesh, состояние и заполнение контекста.",
    taskCaption: "Задача открывает чат с датами, текущим Mesh, полем ответа и управлением рядом.",
    usageCaption: "Usage превращает давление context и наблюдаемые outcomes инструментов в конкретные действия.",
    watchCaption: "Watch нужен для glance, решения, короткого ответа и новой голосовой задачи.",
    openCapture: "Открыть крупно",
    closeCapture: "Закрыть просмотр",
    securityKicker: "Native E2EE",
    securityTitle: "Relay маршрутизирует шифротекст и не может читать задачи.",
    securityText: "Трафик iPhone и Apple Watch защищён сквозным шифрованием. Pairing keys, task keys, credentials, prompts, commands и replies не попадают в relay в читаемом виде.",
    securityFacts: [
      ["На компьютерах", "Coding agents и provider credentials остаются локальными."],
      ["На relay", "Видны только ограниченные routing metadata, шифротекст, expiry и wake metadata."],
      ["На устройствах", "Разрешённые endpoints расшифровывают задачи; ключи задач изолированы."],
    ],
    installKicker: "Установка",
    installTitle: "Установите plugin. Подключитесь на этом компьютере.",
    installText: "Добавьте GrantTap в Codex, Claude Code, Cursor Marketplace или Grok Build и выполните granttap setup. Подключите телефон по QR из панели GrantTap. На Mac с локальным мостом granttap.com/connect также может подтвердить доступ coding app по passkey. Не добавляйте GrantTap в Cursor Customize → MCPs.",
    source: "Исходники",
    npm: "npm",
    relay: "Relay",
    pricingKicker: "Personal",
    pricingTitle: "От $1,99 в месяц после 7 бесплатных дней.",
    pricingText: "$1,99 за один компьютер, $3,99 за пять, $5,99 за десять. Агентов на каждом — без ограничений. Отмена через Apple в любой момент.",
    pricingAction: "Цена и условия",
    releaseKicker: "Доступность",
    releaseTitle: "Отправлено в App Store.",
    releaseText: "GrantTap 1.0 ожидает App Review. Пока Apple проверяет релиз, доступ к TestFlight предоставляется по приглашению.",
    tagline: "Смотрите, что делают coding agents. Подключайтесь, когда вы нужны.",
  },
} as const;

export type HomeCopy = typeof copy.en | typeof copy.ru;
