"use client";

import { HomeView } from "./components/HomeView";
import { useLocale } from "./components/Locale";

export const copy = {
  en: {
    nav: ["Product", "How it works", "Usage", "Security", "Install", "Pricing"],
    cta: "Join TestFlight",
    eyebrow: "Personal live control for local coding agents",
    heroTitle: "All your coding agents.",
    heroAccent: "One live control center.",
    hero: "See what Claude Code, Codex, Cursor, and Grok Build are doing across your computers, what they use, and when they need you. Approve, reply or continue from iPhone and Apple Watch.",
    heroAction: "Join TestFlight",
    productAction: "See the product",
    proofs: ["Claude Code · Codex · Cursor · Grok Build", "Multi-computer", "End-to-end encrypted", "Apple Watch"],
    providers: "Supported integrations",
    cursor: "Cursor Beta",
    grok: "Grok Build · Experimental",
    additional: "Provider-specific controls stay intact",
    productKicker: "See · Decide · Continue",
    productTitle: "Know what is happening now—and where you are needed.",
    productText: "GrantTap joins live local sessions without becoming another coding agent, terminal, or passive analytics dashboard.",
    scenarios: [
      ["Needs You", "Approvals, questions, and failed deliveries appear before everything else."],
      ["Working", "See the agent, model, computer, workspace, and latest useful activity."],
      ["Usage", "Find context pressure, observed tool failures, and actions worth taking."],
      ["Governance", "Allow, ask, or deny skills, MCP servers, and shell per Project—for a whole kind or one named capability. Every computer applies the same policy."],
    ],
    meshKicker: "Project Mesh",
    meshTitle: "One project. Several agents. One human attention layer.",
    meshText: "Agents share compact task state, dependencies, resource claims, and handoff receipts—not transcripts or hidden reasoning. Parallel work uses separate branches or worktrees.",
    meshQuestions: [
      ["Who is working?", "See the agent, computer, task, branch, and current owner."],
      ["Who depends on whom?", "Catch blockers and overlapping resource claims before they become merge conflicts."],
      ["Where are you needed?", "Technical questions stay agent-to-agent. Product, security, destructive, and unresolved conflicts reach Needs You."],
    ],
    howKicker: "How it works",
    howTitle: "One secure path back to the same local task.",
    steps: [
      ["Connect", "Run one setup command, scan one QR, and verify your installed providers."],
      ["Decide", "Allow, deny, answer, or retry when the exact session asks for you."],
      ["Continue", "Open the visible timeline and send the next turn with voice, photos, or files."],
    ],
    galleryKicker: "The real app",
    galleryTitle: "Current work on iPhone. Fast decisions on Apple Watch.",
    phoneCaption: "Now prioritizes Needs You, at-risk work, active sessions, and a short recent list.",
    taskCaption: "The task opens directly into live activity and chat, with context and controls one tap away.",
    usageCaption: "Usage turns context pressure and observed tool outcomes into concrete next actions.",
    watchCaption: "Watch is for a glance, a decision, a short reply, or a new voice task.",
    openCapture: "Open full-size",
    closeCapture: "Close preview",
    securityKicker: "Native E2EE",
    securityTitle: "The relay routes ciphertext. It cannot read your tasks.",
    securityText: "Native iPhone and Apple Watch traffic is end-to-end encrypted. Pairing keys, task keys, provider credentials, prompts, commands, and replies never enter readable relay storage.",
    securityFacts: [
      ["On your computers", "Coding agents and provider credentials stay local."],
      ["On the relay", "Only bounded routing metadata, ciphertext, expiry, and wake metadata are visible."],
      ["On your devices", "Authorized endpoints decrypt the task and keep each task key isolated."],
    ],
    installKicker: "Install",
    installTitle: "One helper. One setup flow.",
    installText: "Setup detects supported providers, installs hooks, starts the background helper, and gives one clear next action.",
    source: "Source",
    npm: "npm",
    relay: "Relay",
    pricingKicker: "Personal",
    pricingTitle: "From $1.99 per month after a 7-day free trial.",
    pricingText: "$1.99 for one computer, $3.99 for five, $5.99 for ten. Unlimited agents on each. Cancel through Apple at any time.",
    pricingAction: "Pricing and terms",
    releaseKicker: "Availability",
    releaseTitle: "Testing before the App Store release.",
    releaseText: "Join TestFlight to try GrantTap on iPhone and Apple Watch before the public release.",
    tagline: "See what your coding agents are doing. Step in when they need you.",
    legal: ["Pricing", "Privacy", "Terms", "Support", "Security", "Data choices", "Accessibility", "Licenses"],
    guides: ["Project Mesh", "Grok Bot", "Apple Watch", "Claude Code", "Codex", "Cursor Beta", "Grok Build"],
    rights: "© 2026 GrantTap. Not affiliated with Anthropic, OpenAI, Anysphere, xAI, or Apple.",
  },
  ru: {
    nav: ["Продукт", "Как работает", "Usage", "Безопасность", "Установка", "Цена"],
    cta: "В TestFlight",
    eyebrow: "Personal live control для локальных coding agents",
    heroTitle: "Все ваши coding agents.",
    heroAccent: "Один live control center.",
    hero: "Смотрите, что делают Claude Code, Codex, Cursor и Grok Build на ваших компьютерах, что они используют и когда им нужен ваш ответ. Разрешайте, отвечайте и продолжайте с iPhone и Apple Watch.",
    heroAction: "В TestFlight",
    productAction: "Посмотреть продукт",
    proofs: ["Claude Code · Codex · Cursor · Grok Build", "Несколько компьютеров", "Сквозное шифрование", "Apple Watch"],
    providers: "Поддерживаемые интеграции",
    cursor: "Cursor Beta",
    grok: "Grok Build · Experimental",
    additional: "Provider-specific controls сохраняются",
    productKicker: "See · Decide · Continue",
    productTitle: "Понимайте, что происходит сейчас и где нужны именно вы.",
    productText: "GrantTap объединяет локальные live sessions, не становясь ещё одним coding agent, терминалом или пассивной аналитикой.",
    scenarios: [
      ["Needs You", "Подтверждения, вопросы и ошибки доставки всегда выше остального."],
      ["Working", "Видны agent, model, computer, workspace и последнее полезное событие."],
      ["Usage", "Давление context, наблюдаемые ошибки tool calls и конкретные действия."],
      ["Governance", "Разрешайте, спрашивайте или запрещайте skills, MCP-серверы и shell для Project — целиком по виду или для одной названной возможности. Политику применяет каждый компьютер."],
    ],
    meshKicker: "Project Mesh",
    meshTitle: "Один проект. Несколько агентов. Один human-attention layer.",
    meshText: "Агенты делятся компактным состоянием задач, dependencies, resource claims и handoff receipts — без transcript и hidden reasoning. Параллельная работа идёт в отдельных branches или worktrees.",
    meshQuestions: [
      ["Кто работает?", "Видны agent, computer, task, branch и текущий owner."],
      ["Кто от кого зависит?", "Blockers и пересекающиеся resource claims обнаруживаются до merge conflict."],
      ["Где нужны вы?", "Технические вопросы остаются между агентами. Product, security, destructive и неразрешимые конфликты попадают в Needs You."],
    ],
    howKicker: "Как работает",
    howTitle: "Один защищённый путь обратно в ту же локальную задачу.",
    steps: [
      ["Подключите", "Запустите одну setup-команду, отсканируйте QR и проверьте установленные providers."],
      ["Решите", "Разрешите, запретите, ответьте или повторите доставку для точной session."],
      ["Продолжите", "Откройте timeline и отправьте следующий ход голосом, с фото или файлом."],
    ],
    galleryKicker: "Настоящее приложение",
    galleryTitle: "Текущая работа на iPhone. Быстрые решения на Apple Watch.",
    phoneCaption: "Now сначала показывает Needs You, риски, активные задачи и короткий recent list.",
    taskCaption: "Задача сразу открывает live activity и chat; context и controls доступны одним касанием.",
    usageCaption: "Usage превращает давление context и наблюдаемые outcomes инструментов в конкретные действия.",
    watchCaption: "Watch нужен для glance, решения, короткого ответа и новой голосовой задачи.",
    openCapture: "Открыть крупно",
    closeCapture: "Закрыть просмотр",
    securityKicker: "Native E2EE",
    securityTitle: "Relay маршрутизирует шифротекст и не может читать задачи.",
    securityText: "Трафик iPhone и Apple Watch защищён сквозным шифрованием. Pairing keys, task keys, credentials, prompts, commands и replies не попадают в relay в читаемом виде.",
    securityFacts: [
      ["На компьютерах", "Coding agents и provider credentials остаются локальными."],
      ["На relay", "Видны только ограниченные routing metadata, шифротекст, expiry и wake metadata."],
      ["На устройствах", "Разрешённые endpoints расшифровывают задачи; ключи задач изолированы."],
    ],
    installKicker: "Установка",
    installTitle: "Один helper. Один setup flow.",
    installText: "Setup находит providers, устанавливает hooks, запускает background helper и даёт одно понятное следующее действие.",
    source: "Исходники",
    npm: "npm",
    relay: "Relay",
    pricingKicker: "Personal",
    pricingTitle: "От $1,99 в месяц после 7 бесплатных дней.",
    pricingText: "$1,99 за один компьютер, $3,99 за пять, $5,99 за десять. Агентов на каждом — без ограничений. Отмена через Apple в любой момент.",
    pricingAction: "Цена и условия",
    releaseKicker: "Доступность",
    releaseTitle: "Тестирование перед релизом в App Store.",
    releaseText: "Присоединяйтесь к TestFlight, чтобы попробовать GrantTap на iPhone и Apple Watch.",
    tagline: "Смотрите, что делают coding agents. Подключайтесь, когда вы нужны.",
    legal: ["Цена", "Конфиденциальность", "Условия", "Поддержка", "Безопасность", "Данные", "Доступность", "Лицензии"],
    guides: ["Project Mesh", "Grok Bot", "Apple Watch", "Claude Code", "Codex", "Cursor Beta", "Grok Build"],
    rights: "© 2026 GrantTap. Не связан с Anthropic, OpenAI, Anysphere, xAI или Apple.",
  },
} as const;

export type HomeCopy = typeof copy.en | typeof copy.ru;

export default function Home() {
  const { locale, setLocale } = useLocale();
  return <HomeView locale={locale} setLocale={setLocale} t={copy[locale]} />;
}
