import type { Metadata } from "next";
import { LegalPage } from "../components/LegalPage";

export const metadata: Metadata = { title: "Support", description: "Install, connect, and troubleshoot GrantTap Personal.", alternates: { canonical: "/support" } };

export default function SupportPage() {
  return <LegalPage
    title={{ en: "Support", ru: "Поддержка" }}
    updated={{ en: "October 5, 2026", ru: "5 октября 2026" }}
    updatedISO="2026-10-05"
    intro={{ en: "Install the runtime, run setup, and authenticate the coding app. The one-time QR stays in the GrantTap connection card and is scanned on the phone — never in chat.", ru: "Установите runtime, выполните setup и подтвердите coding app. Одноразовый QR находится в панели подключения GrantTap и сканируется телефоном — не в чате." }}
    art={{ src: "/visuals/pairing-journey.jpg", width: 1774, height: 887, caption: { en: "Conceptual pairing illustration. The tile is not a working QR code or a screenshot; use the one-time code in your own GrantTap connection card.", ru: "Концептуальная иллюстрация подключения. Плитка не является рабочим QR-кодом или снимком экрана; используйте одноразовый код в своей панели GrantTap." } }}
    sections={{
      en: [
        { heading: "Account passkey and QR", paragraphs: ["An Account Mesh exists as soon as you create or sign in to your Personal account, even with no computer. It can contain many Projects and their Meshes. Use the same passkey in GrantTap MCP to add a computer; each Task keeps its own computer route. A one-time QR still offers a direct device link.", "A GrantTap passkey is not Sign in with Apple. Apple Passwords can sync it through iCloud if you save it there. If you choose another passkey manager, use that same provider on the Mac, possibly with your phone. On the Mac, link the account from the GrantTap MCP connection card or the Mac app; the Mac app needs local MCP access.", "On a Mac with the local GrantTap bridge, granttap.com/connect can request a fresh passkey assertion to approve one coding-app connection. The Mac must still authorize its local MCP bridge. You can review and revoke account devices in the account page."] },
        { heading: "Mac app and device connections", bullets: ["Open Help → GrantTap Help for built-in guides. GrantTap → About GrantTap shows the version, purchase options, Terms, Privacy and licenses. These documents remain readable offline.", "In the Mac app, open Devices → Connect iPhone or iPad for a one-time QR. On the phone or tablet, open Devices → Add a device (Scan QR).", "To add a Mac or PC, choose Connect a computer by link and paste its one-time invitation. Existing device connections are preserved.", "Install the separate MCP helper on this Mac. A release build needs Authorize local Mac access; provider hooks may also need review in Codex."] },
        { heading: "Purchase, restore and connection modes", paragraphs: ["The launch Mac License is planned at $39.99 in the US; Apple supplies the actual local price and availability. Personal is optional: $1.99 / $3.99 / $5.99 per month for 1 / 5 / 10 computers, with the eligible trial shown by Apple. Model tokens are separate.", "Use Restore purchases in Settings with the same Apple Account that made the purchase. Manage subscription opens Apple's controls. Deleting the app does not cancel a subscription.", "A licensed Mac can use managed delivery with Personal, direct delivery using encrypted address discovery without Personal, or a fully self-hosted relay. Configure Devices → Device network → Connection mode & own relay. Direct and self-hosted delivery need a reachable TLS endpoint or VPN; an announced IP alone cannot cross NAT. You maintain your own server and backups. Background notifications require a suitable push service."] },
        { heading: "Connect a computer", bullets: ["Install Node.js 22 or newer.", "Run npm install -g granttap-mcp.", "Run granttap setup. It detects providers, installs supported hooks, and starts or repairs the helper.", "Open the GrantTap connection card in the coding app and choose Add a device. Scan its one-time QR in GrantTap on iPhone.", "Use Add another device for a second phone or Reconnect for the same phone. granttap.com/connect handles coding-app approval and observations, not the QR.", "Use granttap status for a read-only readiness summary."] },
        { heading: "Provider readiness", bullets: ["Claude Code and Codex are the primary integrations.", "Codex may require you to trust the exact GrantTap hooks before restarting Codex.", "For Cursor, install the GrantTap Marketplace listing, then run granttap setup. Its supported controls are described in the Cursor guide. Do not add GrantTap in Customize → MCPs.", "Grok Build controls depend on what the installed local runtime exposes.", "Cursor Cloud · fetch failed is a leftover user HTTP MCP at 127.0.0.1:17342, or the unused cloud plugin source — not proof the phone is unpaired.", "A provider that is not installed is not an error."] },
        { heading: "Pairing or delivery does not work", bullets: ["Confirm internet access and use a wss:// relay URL.", "A website “seen” or Connected label is an observation, not Live. Live is visible in GrantTap after the helper and phone share a room.", "A phone without a room adopts the computer's room. If already Live, it keeps its room and the computer joins it. Reconnect mints a QR for the same room.", "Open GrantTap on the unlocked iPhone. A locked phone stays offline.", "Check iOS Notifications and Background App Refresh. APNs timing is controlled by Apple and cannot be guaranteed.", "Never send pairing tokens, room credentials, provider credentials, prompts, or repository paths in support messages."] },
        { heading: "Contact and diagnostics", paragraphs: ["Email sergii.ziborov@gmail.com with app, iOS/watchOS, Node.js, helper, and provider versions plus sanitized reproduction steps. Export diagnostics from the app's Troubleshooting destination when available."], links: [{ label: "MCP/helper issues", href: "https://github.com/sergii-ziborov/granttap-mcp/issues" }, { label: "Relay issues", href: "https://github.com/sergii-ziborov/granttap-relay/issues" }] },
      ],
      ru: [
        { heading: "Passkey аккаунта и QR", paragraphs: ["Mesh аккаунта появляется после создания аккаунта или входа в него даже без компьютера. Он может содержать множество проектов и их Mesh. Тот же passkey в GrantTap MCP добавит компьютер; каждая задача сохранит свой маршрут. Одноразовый QR также даёт прямое подключение устройства.", "Passkey GrantTap — не функция «Войти с Apple». Если сохранить его в Apple Passwords, он может синхронизироваться через iCloud. Если выбрать другой менеджер, используйте его же на Mac, при необходимости через телефон. На Mac привяжите аккаунт через панель подключения GrantTap MCP или Mac-приложение; приложению нужен локальный доступ к MCP.", "На Mac с локальным мостом GrantTap страница granttap.com/connect может запросить новый passkey для разрешения доступа одной coding app. Mac отдельно подтверждает доступ к локальному MCP. Устройства аккаунта можно просмотреть и отключить на странице аккаунта."] },
        { heading: "Mac и подключение устройств", bullets: ["Откройте Help → GrantTap Help для встроенной справки. GrantTap → About GrantTap показывает версию, покупки, условия, конфиденциальность и лицензии. Документы доступны без интернета.", "На Mac откройте Devices → Connect iPhone or iPad для одноразового QR. На телефоне или планшете: Devices → Add a device (Scan QR).", "Для подключения Mac или PC выберите Connect a computer by link и вставьте его одноразовое приглашение. Существующие подключения сохраняются.", "Установите отдельный MCP helper на этом Mac. В релизе требуется Authorize local Mac access; hooks провайдера могут отдельно требовать проверки в Codex."] },
        { heading: "Покупка, восстановление и режимы связи", paragraphs: ["Стартовая лицензия Mac планируется за $39,99 в США; доступность и локальную цену показывает Apple. Personal необязательна: $1,99 / $3,99 / $5,99 в месяц за 1 / 5 / 10 компьютеров. Пробный период для подходящего покупателя показывает Apple. Токены модели оплачиваются отдельно.", "Нажмите Restore purchases в Settings с тем же Apple Account, с которого покупали. Manage subscription открывает управление Apple. Удаление приложения не отменяет подписку.", "Лицензированный Mac работает через управляемую доставку с Personal, напрямую с зашифрованным поиском адреса без Personal или через полностью свой relay. Настройка: Devices → Device network → Connection mode & own relay. Для прямой связи и своего relay нужен доступный TLS endpoint или VPN; объявление IP не обходит NAT. Сервером и резервными копиями управляете вы. Для фоновых уведомлений нужен соответствующий push-сервис."] },
        { heading: "Подключить компьютер", bullets: ["Установите Node.js 22 или новее.", "Выполните npm install -g granttap-mcp.", "Выполните granttap setup. Команда найдёт providers, установит hooks и запустит или исправит helper.", "В панели GrantTap в coding app выберите Add a device и отсканируйте одноразовый QR приложением на iPhone.", "Для второго телефона используйте Add another device, для того же — Reconnect. granttap.com/connect служит для подтверждения coding app и наблюдения, а не для QR.", "granttap status показывает read-only readiness summary."] },
        { heading: "Готовность providers", bullets: ["Claude Code и Codex — основные интеграции.", "Для Cursor установите GrantTap из Marketplace и выполните granttap setup. Поддерживаемые способы управления описаны в руководстве Cursor. Не добавляйте GrantTap в Customize → MCPs.", "Доступные способы управления Grok Build зависят от установленного локального runtime.", "Codex может потребовать доверить точные GrantTap hooks и перезапустить Codex.", "Cursor Cloud · fetch failed — лишний user HTTP MCP на 127.0.0.1:17342 или cloud-источник плагина, а не доказательство, что телефон не спарен.", "Неустановленный provider не является ошибкой."] },
        { heading: "Не работает pairing или delivery", bullets: ["Проверьте интернет и wss:// relay URL.", "«Seen» или Connected на сайте — наблюдение, но не Live. Live видно в GrantTap, когда helper и телефон в одной комнате.", "Телефон без комнаты принимает комнату компьютера. Если телефон уже Live, он сохраняет комнату, а компьютер подключается к ней. Reconnect даёт QR той же комнаты.", "Откройте GrantTap на разблокированном iPhone. Заблокированный телефон остаётся offline.", "Проверьте iOS Notifications и Background App Refresh. Время APNs определяет Apple и оно не гарантируется.", "Не отправляйте в поддержку pairing tokens, room credentials, provider credentials, prompts или repository paths."] },
        { heading: "Контакт и diagnostics", paragraphs: ["Напишите на sergii.ziborov@gmail.com версии приложения, iOS/watchOS, Node.js, helper и provider, а также очищенные шаги воспроизведения. При наличии экспортируйте diagnostics из Troubleshooting."], links: [{ label: "Проблемы MCP/helper", href: "https://github.com/sergii-ziborov/granttap-mcp/issues" }, { label: "Проблемы relay", href: "https://github.com/sergii-ziborov/granttap-relay/issues" }] },
      ],
    }}
  />;
}
